### ISSUE TITLE
Can't use driver with Ros Kinetic.

### ISSUE THREAD

**Issue by wnightvn** [CWRUProjectRaptor/Delta-2B-Lidar-SDK#1]
i followed you instruction in Delta_2A_ros, but i cant make it work. Actually, everything was fine until i did the command "roslaunch delta_lidar view_delta_lidar.launch". The ros's terminal of node and rviz keep getting the error "[CSerialConnection]::read Blocking read failed", "[CLidarPacketReceiver] CRC verify wrong!" and some is in the image.
I am using Ubuntu 16.04, ros kinetic.

Everything is fine...
![image](https://user-images.githubusercontent.com/76776653/103349743-40751500-4ad0-11eb-8857-4e3c5f929eef.png)
![image](https://user-images.githubusercontent.com/76776653/103349808-75816780-4ad0-11eb-99cc-ac529d647c8f.png)
until i open the .launch file:
![image](https://user-images.githubusercontent.com/76776653/103349868-ac577d80-4ad0-11eb-816b-c40ba53c676d.png)

**Comment by frank-qcd-qk** [comment]
The code is tested on ROS Melodic only.

**Comment by frank-qcd-qk** [comment]
It looks like the connection to usb is severed.
